### ISSUE TITLE
Need to add GUI to generate dates to make commits

### ISSUE THREAD

**Issue by gaurav-kay** [gaurav-kay/GitHub-Art#1]
Description: Having a Canvas-like GUI with the contributions graph aligned with the current date is needed. We also need to consider the different shades of green that can be used. Which will be calculated relatively, considering the commits per day

**Comment by conk3r353** [comment]
Hi! I would like to work on this issue.

**Comment by gaurav-kay** [comment]
Hi! Thanks for taking an interest. 
I will update the README soon, but until then, familiarise yourself with the code and the objective. We need a GUI that allows users to, ideally, click over a grid identical to the contributions graph. So that we can extract the dates to be passed on to the script, which as of now takes in hard coded dates

**Comment by bhaveshpatel640** [comment]
Haha, today itself, I thought of it and changed the Html code for it to check how it looks. :P 

![Screenshot from 2019-09-26 12-22-22](https://user-images.githubusercontent.com/21009675/65667316-1cb95880-e05d-11e9-8225-9cd8024e8ef8.png)


Just one thought, Instead of date and time, we should take a string as an input, and rest code will handle on its own, this would be tough one by definitely an interesting one.  What say?
I can help you out in this.

**Comment by conk3r353** [comment]
Definitely sounds like an interesting one. Also should be doable. I'll see what I can do.

**Comment by gaurav-kay** [comment]
Hi @bhaveshpatel640! Thanks for checking this project out. 
What you suggested can be done! But we don't want to restrict art to only words and ASCII characters! Which is why having a canvas-like GUI with the contributions graph as a background would allow any art to be done!

**Comment by bhaveshpatel640** [comment]
True, This will extend its capabilities even more. :)

**Comment by conk3r353** [comment]
By the way, how should I give out picked dates? Right now I'm thinking of putting them in a json file. Will it do? Or should I just execute the script immediately with entered dates?

**Comment by gaurav-kay** [comment]
Oh nice! Can you fork this repo and add changes there? so that we can see the code. Also how are you making the GUI? If it's with python itself, we can run the committing script after they click a button or something. Even a JSON file is fine!

**Comment by conk3r353** [comment]
@gaurav-kay I'm using PyQt, so there should be no problem in launching a script from GUI. I'll make a fork ASAP.

**Comment by gaurav-kay** [comment]
This issue is now closed. @conk3r353 has helped in adding the GUI (#2 ). Further modifications to it, like adding varying number commit by clicking twice, for example are welcome through pull requests. Thanks!
